Add Linux x86 Builds

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -31,8 +31,48 @@ jobs:
     - name: Upload Artifacts
       uses: actions/upload-artifact@v2
       with:
-        name: linux_binary
+        name: linux-x86_64
         path: csprite.elf
+        if-no-files-found: error
+
+  linux_i686:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v2
+      with:
+        submodules: recursive
+
+    - name: Install Pillow & Numpy
+      run: |
+        python3 -m pip install --upgrade Pillow
+        python3 -m pip install --upgrade numpy
+
+    - name: Generate Assets
+      run: |
+        python3 tools/create_icons.py
+        python3 tools/create_assets.py
+
+    - name: Setup Ubuntu 18.04 x86
+      uses: paulproteus/ubuntu-18.04-x86@0.1
+      with:
+        command: |
+          apt-get update -y
+          apt-get install -y libglfw3 libglfw3-dev pkg-config git libgtk-3-dev scons
+          make release
+          mv csprite csprite-i686.elf
+
+    - name: Exit if file not exists
+      run: |
+        if [ ! -e ./csprite-i686.elf ]; then
+            echo "'csprite-i686.elf' executable not found"
+            exit 1
+        fi
+
+    - name: Upload Artifacts
+      uses: actions/upload-artifact@v2
+      with:
+        name: linux-i686
+        path: ./csprite-i686.elf
         if-no-files-found: error
 
   windows-x86_64:
@@ -65,7 +105,7 @@ jobs:
       - name: Upload Artifacts
         uses: actions/upload-artifact@v2
         with:
-          name: win_binary
+          name: win-x86_64
           path: csprite-x86_64.exe
           if-no-files-found: error
 
@@ -99,7 +139,7 @@ jobs:
       - name: Upload Artifacts
         uses: actions/upload-artifact@v2
         with:
-          name: win_binary
+          name: win-i686
           path: csprite-i686.exe
           if-no-files-found: error
 
