Add Linux x86 Builds

diff --git a/.github/workflows/stable.yml b/.github/workflows/stable.yml
--- a/.github/workflows/stable.yml
+++ b/.github/workflows/stable.yml
@@ -47,8 +47,48 @@ jobs:
     - name: Upload Artifacts
       uses: actions/upload-artifact@v2
       with:
-        name: linux_binary
+        name: linux-x86_64
         path: csprite-x86_64.elf
+        if-no-files-found: error
+
+  linux_i686:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v2
+      with:
+        submodules: recursive
+
+    - name: Install Pillow & Numpy
+      run: |
+        python3 -m pip install --upgrade Pillow
+        python3 -m pip install --upgrade numpy
+
+    - name: Generate Assets
+      run: |
+        python3 tools/create_icons.py
+        python3 tools/create_assets.py
+
+    - name: Setup Ubuntu 18.04 x86
+      uses: paulproteus/ubuntu-18.04-x86@0.1
+      with:
+        command: |
+          apt-get update -y
+          apt-get install -y libglfw3 libglfw3-dev pkg-config git libgtk-3-dev scons
+          make release
+          mv csprite csprite-i686.elf
+
+    - name: Exit if file not exists
+      run: |
+        if [ ! -e ./csprite-i686.elf ]; then
+            echo "'csprite-i686.elf' executable not found"
+            exit 1
+        fi
+
+    - name: Upload Artifacts
+      uses: actions/upload-artifact@v2
+      with:
+        name: linux-i686
+        path: ./csprite-i686.elf
         if-no-files-found: error
 
   windows-x86_64:
@@ -81,7 +121,7 @@ jobs:
       - name: Upload Artifacts
         uses: actions/upload-artifact@v2
         with:
-          name: win_binary
+          name: win-x86_64
           path: csprite-x86_64.exe
           if-no-files-found: error
 
@@ -115,7 +155,7 @@ jobs:
       - name: Upload Artifacts
         uses: actions/upload-artifact@v2
         with:
-          name: win_binary
+          name: win-i686
           path: csprite-i686.exe
           if-no-files-found: error
 
@@ -189,15 +229,23 @@ jobs:
       uses: actions/checkout@v2
 
     - name: Clean previous binaries
-      run: rm -f csprite csprite.exe
+      run: rm *.elf *.exe *.zip
 
     - uses: actions/download-artifact@v2
       with:
-        name: linux_binary
+        name: linux-x86_64
 
     - uses: actions/download-artifact@v2
       with:
-        name: win_binary
+        name: linux-i686
+
+    - uses: actions/download-artifact@v2
+      with:
+        name: win-x86_64
+
+    - uses: actions/download-artifact@v2
+      with:
+        name: win-i686
 
     - uses: actions/download-artifact@v2
       with:
@@ -212,6 +260,7 @@ jobs:
         title: "csprite v${{github.event.inputs.MajVer}}.${{github.event.inputs.MinVer}}.${{github.event.inputs.PatVer}}"
         files: |
           csprite-x86_64.elf
+          csprite-i686.elf
           csprite-x86_64.exe
           csprite-i686.exe
           csprite-osx.zip
